import Head from "next/head";
import "bootstrap/dist/css/bootstrap.css";
import Card from "react-bootstrap/Card";
import Navbar from "../components/navbar";
import Layout from "../components/layout";
import { Container } from "react-bootstrap";
import PostList from "../components/postList";

export default function Home() {
  return (
    <>
      <Layout>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="container">
          <Card>
            <Card.Body>
              <h1>Welcome to Pet Story</h1>
              <Container>
                <PostList />
              </Container>
            </Card.Body>
          </Card>
        </div>
      </Layout>
    </>
  );
}
